package com.skillmagnet.Course;

import java.time.LocalDateTime;

import org.hibernate.annotations.CreationTimestamp;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Data;

@Data
@Entity
@Table(name = "course")
public class Course {
    @Id
    @GeneratedValue
    private int id;

    private String title;
    private String description;
    private String category;
    private int views;
    private int thumbsUp;
    private int thumbsDown;

    @CreationTimestamp
    private LocalDateTime createdAt;
    @CreationTimestamp
    private LocalDateTime status;

    // Breaks w/ out
    public Course() {}

    public Course(String title, String description, String category, int views, 
        int thumbsDown, int thumbsUp){
        // the following values are the only ones that need to be initialized
        // the timestamps and id's are autogenerated during a post request
        this.title = title;
        this.description = description;
        this.category = category;
        this.views = views;
        this.thumbsDown = thumbsDown;
        this.thumbsUp = thumbsUp;
    }
}
