package com.skillmagnet.Course;

import java.sql.Timestamp;

import org.hibernate.annotations.CreationTimestamp;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

@Entity
@Table(name = "course")
public class Course {
    @Id
    @GeneratedValue
    private int id;

    private String title;
    private String description;
    private String category;
    private int views;
    private int thumbsUp;
    private int thumbsDown;

    @CreationTimestamp
    private Timestamp createdAt;
    @CreationTimestamp
    private Timestamp status;

    public Course() {}

    public Course(String title, String description, String category,
        Timestamp createdAt, Timestamp status, int views, 
        int thumbsDown, int thumbsUp){
        // the following values are the only ones that need to be initialized
        // the timestamps and id's are autogenerated during a post request
        this.title = title;
        this.description = description;
        this.category = category;
        this.views = views;
        this.thumbsDown = thumbsDown;
        this.thumbsUp = thumbsUp;
    }

    // Getter and Setter for 'title'
    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    // Getter and Setter for 'description'
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    // Getter and Setter for 'category'
    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    // Getter and Setter for 'createdAt'
    public Timestamp getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    // Getter and Setter for 'status'
    public Timestamp getStatus() {
        return status;
    }

    public void setStatus(Timestamp status) {
        this.status = status;
    }

    public int getViews() {
        return views;
    }

    // Setter method for views
    public void setViews(int views) {
        this.views = views;
    }

    // Getter method for thumbsUp
    public int getThumbsUp() {
        return thumbsUp;
    }

    // Setter method for thumbsUp
    public void setThumbsUp(int thumbsUp) {
        this.thumbsUp = thumbsUp;
    }

    // Getter method for thumbsDown
    public int getThumbsDown() {
        return thumbsDown;
    }

    // Setter method for thumbsDown
    public void setThumbsDown(int thumbsDown) {
        this.thumbsDown = thumbsDown;
    }
    
}
