name: SkillMagnet Development Branch Actions

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-publish-artifact:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Clone Github Repo
        uses: actions/checkout@v2

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install NPM Dependencies & Create Frontend Build
        working-directory: ./client
        run: |
          npm install
          npm run build
        env:
          VITE_API_URL_BASE: /api/
          VITE_AWS_S3_PUBLIC_KEY: ${{ secrets.AWS_S3_PUBLIC_KEY }}
          VITE_AWS_S3_SECRET_KEY: ${{ secrets.AWS_S3_SECRET_KEY }}

      - name: Copy Frontend Build To Backend Static Files
        run: |
          mkdir server/src/main/resources/static
          cp -R ./client/dist/* ./server/src/main/resources/static/

      - name: Install Java 21
        uses: actions/setup-java@v1
        with:
          java-version: 21

      - name: Build Backend with Maven
        working-directory: ./server/
        run: mvn -B package -DskipTests --file pom.xml
