name: SkillMagnet Release CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-publish-artifact:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Clone Github Repo
        uses: actions/checkout@v2

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install NPM Dependencies & Create Frontend Build
        working-directory: ./client
        run: |
          npm install
          npm run build

      - name: Copy Frontend Build To Backend Static Files
        run: |
          mkdir server/src/main/resources/static
          cp -R ./client/dist/* ./server/src/main/resources/static/

      - name: Install Java 21
        uses: actions/setup-java@v1
        with:
          java-version: 21

      - name: Build Backend with Maven
        working-directory: ./server/
        run: mvn -B package -DskipTests --file pom.xml

      - name: Upload Artifact to S3
        run: |
          aws s3 cp ./server/target/server-0.0.1-SNAPSHOT.jar s3://skillmagnet
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"

  deploy:
    needs: build-publish-artifact
    runs-on: ubuntu-latest

    steps:
      - name: Clone Github Repo
        uses: actions/checkout@v2

      - name: Create CodeDeploy Deployment
        run: |
          commit_hash=`git rev-parse HEAD`
          aws deploy create-deployment --application-name skill-magnet --deployment-group-name prod --github-location repository=$GITHUB_REPOSITORY,commitId=$commit_hash --ignore-application-stop-failures
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
